import "./globals.scss";

// import { DM_Sans } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });
// const dm = DM_Sans({ subsets: ['latin'], weight: ['700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
